# -*- coding: utf-8 -*-
"""python1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12AGoKGethb1XhLKKUo-ypfId0afzlu7M
"""

import numpy as np

arr2 = np.zeros((1,4))

import numpy as np
arr1 = np.array([[[1,2,3,4],
                  [2,3,4,5],
                  [1,7,8,5]],

                  [[1,2,3,4],
                  [3,2,1,3],
                  [2,3,1,2]]])

arr1
arr2

arr1.ndim

arr1[0][1,:2]

data1 = np.array([[[1,2,3,4],
                   [5,6,7,8]],
                 
                  [[9,10,11,12],
                  [13,14,15,16],
                  [1,2,3,4]],
                 
                  [[1,2,3,44],
                  [1,2,3,4,5]]])
data1.ndim

data5 = np.array([[[1,2,3,4],
                   [5,6,7,8]],
                 
                  [[9,10,11,12],
                  [13,14,15,16],
                  [1,2,3,4]],
                 
                 [[1,2,3,44],
                 [1,2,3,4,5]]])
data5.ndim

data5.ndim

arr2 = np.zeros((1,4))

arr2

arr2.ndim

data = ["Jamshid","Jamshid","Jamshid"]

import numpy as np
data = np.array(["Jamshid","Ahmadov","Jamshid"])

data.ndim

data == "Jamshid"

data1 = np.random.randn(7,4)

data1
data.ndim



data = np.array(["Jamshid","Ahmadov","Jamshid"])

bol = np.random.randn(3,2)

bol

bol[data=="Jamshid"]

y=np.random.randn(3,3)

y

y[y>0]=1

y

print("I AM JUNIOR")

print("but I will be Senior")

a=np.random.randn(4,3)

a

a.ndim

s= np.arange(1,122)

s

print(s)

s=np.array(s)

import numpy as np

numbers=np.arange(12).reshape(4,3)

numbers

numbers.T

k=numbers

k



numbers

numbers.swapaxes(1,0)

numbers.swapaxes(0,1)

numbers.swapaxes(1,1)

a=int(input())

np.sqrt(numbers)

np.exp(numbers)

arr=np.array([1,2,3,4,5])
arr1=np.array([2,2,2,2,2])

np.power(arr,arr1)

np.mod(arr, arr1)

import numpy as np

arr1 = np.array([1,1,1,1,1,1])
arr2 = np.array([3,4,5,6,7,8])

re = np.where(arr1>4, arr1, arr2)

re

re = np.where(arr2>4, arr1, arr2)
re

g=np.array([1,0,1,1,1,1])

re=np.where(g == 1,arr1,arr2)

re

re.ndim

# r=int(input())
# if r>10:
#   print("HELLO WORLD")

arr1.ndim

numbers.ndim

array=np.arange(10)

m = array*2

m

m
array

array1=np.arange(10,20)

array1*array

nm=array*array1

nm

nm[-1]

nm[4] =0
nm

array.mean()

array.mean(axis=0)

array=np.arange(12).reshape(3,4)

array

array.mean(axis=0)

array.mean(axis=1)

import numpy as np

import numpy as np

arr=np.random.rand(6)

arr

arr.sort()
arr

arr=np.random.randn(11)

arr

arr1 = -np.sort(-arr)

arr1

print(arr1.sort())

print(-arr1)

print(arr1)

arr23=np.random.randn(2,4)

arr23

row = np.sort(arr23, axis=0)

row

row=np.sort(arr23, axis=1)

row

arr1 = np.array(["Jamshid","Jamshid","Ahmadov"])
arr1

np.unique(arr1)

arr2=np.array(["Jamshid","1212"])

np.in1d(arr2,arr1)

k = np.setdiff1d(arr2,arr1)
k1 = np.setdiff1d(arr1,arr2)

k,k1

arr=np.arange(56)
arr_2=np.arange(34)

np.save("datas",arr)

np.savez("arrays", a=arr, b=arr_2)

array_basic = np.load("arrays.npz")

array_basic['a']

import numpy as np
ary=np.array([1,2,3,4,5,8])
ary=ary+1
print(ary[1])

a=np.array([[1,2],[3,4]])
print(a.itemsize)

array_nig = np.arange(1,1000)



"""nothing"""

